### ISSUE TITLE
Bubbles 2000 license?

### ISSUE THREAD

**Issue by arne-cl** [madmaxmatze/coding90s#1]
Hallo Mathias,

schön, dass es euer frühes Meisterwerk bis zu Github geschafft hat!
Unter welcher Lizenz steht denn das Spiel?

Viele Grüße
Arne

**Comment by mathias-work** [comment]
Gute Frage. Im Grunde bin ich da für eine ziemlich freie Nutzung, müsste mich aber mal für eine License entscheiden.

Was hast du denn vor?

**Comment by arne-cl** [comment]
Ich hab noch nichts Konkretes vor. Ich würde wahrscheinlich ein bißchen mit Lazarus rumspielen und sehen
wie gut sich das "cross-compilen" lässt.

Von mir aus reicht da GPLv3 völlig aus, in den Spielemarkt werde ich in diesem Leben wohl nicht mehr einsteigen.
